version: '3'
services:
  redis:
    image: redis:latest
    container_name: docker-redis
    ports:
        - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./conf.d/redis/redis.conf:/usr/local/etc/redis/redis.conf
  
  api:
    container_name: thinker-api
    build: .
    environment:
      - FLASK_APP=api.py
    command: flask run --host=0.0.0.0
    volumes:
      - .:/usr/src/app/
    depends_on:
      - thinker

  thinker:
    container_name: thinker-microservice
    build: .
    environment:
      - FLASK_APP=api.py
    command: python thinker.py
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
    ports:
      - "5001:8000"

  nginx:
    image: "nginx:latest"
    container_name: docker-nginx
    ports:
      - "8080:80"
    volumes:
      - ./conf.d/nginx/:/etc/nginx/conf.d
    depends_on:
      - api